### ISSUE TITLE
Thoughts on capf vs citar-insert-citation for org?

### ISSUE THREAD

**Issue by bdarcus** [mclear-tools/dotemacs#2]
Not sure how I stumbled on this, @mclearc, but I did, and noticed that you're using corfu and cape with company-bibtex.

How are you finding that?

I've been going back and forth on the best path forward for citation insertion and editing, given the recent removal of consult-crm.

I suppose an easy option is just put an example config like your's on the citar wiki as one option?

**Comment by mclearc** [comment]
I like company-bibtex a lot. It isn't quite as good using cape because it doesn't provide all the extra reference info that using it with company did, but it is still mostly all i need in most situations. I hadn't realized that consult-crm was going to go away. And I agree with others in the #582 issue thread that crm provided a really nice ui for citar-insert-citation. But capf is good enough in most use cases. 

Ideally I'd like to port company-bibtex over to corfu/capf entirely. But since my elisp skills are pretty meager that has been on the back burner. Certainly in the meantime you're welcome to link my config to citar's wiki as a sample alternative.

**Comment by bdarcus** [comment]
What are the actual candidates?

I have periodically experimented with writing a capf that uses the citar completion table. But I always get stuck!

**Comment by mclearc** [comment]
Here's how it looks in a basic setting (similar for markdown though...)

<img width="397" alt="Screen Shot 2022-05-12 at 15 49 15" src="https://user-images.githubusercontent.com/1502422/168156661-0588de7d-9b07-4184-990a-32c5c8ca389b.png">

**Comment by bdarcus** [comment]
OK, so it's completing the keys, and using the other data as annotations.

I think I've struggled with my approach because, as with `citar-insert-citation`, the candidates are the full display strings, which you complete against, and then the exit-function inserts the key.

![Screenshot from 2021-06-03 10-45-42](https://user-images.githubusercontent.com/1134/120664569-08944400-c459-11eb-943f-5b66422e4c39.png)

I actually included this [earlier](https://github.com/bdarcus/citar/pull/132), but removed it because I couldn't get the activation to work the way I wanted.

**Comment by mclearc** [comment]
Cool -- I'll have to play around with this. I'd like more info than I'm currently getting with company-bibtex using corfu/cape so your implementation looks interesting. But it sounds like we need to solve the issue of `@` always attempting to complete using citar.

**Comment by bdarcus** [comment]
> But it sounds like we need to solve the issue of `@` always attempting to complete using citar.

That's right.

I think where I got stuck is I could either get the regex to be too greedy (to activate when it shouldn't), or too strict (not at all).

I'm sure in the end there's an obvious solution; I just hadn't found it.

**Comment by mclearc** [comment]
yeah -- company-bibtex w/cape only activates in the relevant modes and only with the keybind completion so extraneous popups of the capf have never been an issue for me.

**Comment by bdarcus** [comment]
I was just looking through my emails, I saw a suggestion from the org-cite developer/maintainer, with something like [this](https://gist.github.com/bdarcus/7e047c8d368618e8b7a267eef535cae2) (untested).

**Comment by mclearc** [comment]
> I was just looking through my emails, I saw a suggestion from the org-cite developer/maintainer, with something like [this](https://gist.github.com/bdarcus/7e047c8d368618e8b7a267eef535cae2) (untested).

That actually works decently well. I'm implementing it with:

```emacs-lisp
(add-hook 'completion-at-point-functions
          #'citar-complete-key-at-point-org-cite
          'append)
```
I think this is the right way to do that. If you were to stick with something like this you would need to generalize it so that it works with markdown and latex. But that seems like it shouldn't be very hard to do. **EDIT**: I need to do more testing though.

**EDIT**: yeah on more testing the exit function seems wonkey.

**Comment by bdarcus** [comment]
> If you were to stick with something like this you would need to generalize it so that it works with markdown and latex.

Yes, I was thinking about that, but hadn't come to a conclusion on how to do it.

> ... the exit function seems wonkey.

I'm guessing I wrote that part before the change in the structure of the candidates. Could that be it?

EDIT: what happens if you change `cdr` to `cadr`?

**Comment by mclearc** [comment]
> EDIT: what happens if you change cdr to cadr?

That worked!
<img width="688" alt="Screen Shot 2022-05-12 at 18 47 11" src="https://user-images.githubusercontent.com/1502422/168179714-4206dca6-9b00-46f2-8829-d5504dcc20b3.png">
<img width="262" alt="Screen Shot 2022-05-12 at 18 47 54" src="https://user-images.githubusercontent.com/1502422/168179778-2622970a-149e-4041-b3aa-0e36a818e7dd.png">
